name: First_workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Run a one-line script
        run: echo Hello, World!
      - name: Run a multi-line script
        run: |
            echo Add other actions to job,
            echo test, and deploy your project.
      
